[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.62.2"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://freesign.ru/"
  

[[redirects]]
  from = "/search"
  to = "https://freesign.ru/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
